id = "blueprint"
name = "Blueprint"
version = "0.4.1"
schema_version = 1
authors = ["tfuxu <tfuxu@tutanota.com>"]
description = "Language support for Blueprint (.blp) files"
repository = "https://github.com/tfuxu/zed-blueprint"

[grammars.blueprint]
repository = "https://github.com/smrtrfszm/tree-sitter-blueprint"
commit = "de66f283c6c9b7c270d766c2e4cf95535650ec48"

[language_servers.blueprint]
name = "Blueprint Language Server"
language = "Blueprint"
