id = "blueprint"
name = "Blueprint"
version = "0.4.1"
schema_version = 1
authors = ["tfuxu <tfuxu@tutanota.com>"]
description = "Language support for Blueprint (.blp) files"
repository = "https://github.com/tfuxu/zed-blueprint"

[grammars.blueprint]
repository = "https://github.com/smrtrfszm/tree-sitter-blueprint"
commit = "f2b043912ffbfcf4e9e8d09709b86ab39a4b78ea"

[language_servers.blueprint]
name = "Blueprint Language Server"
language = "Blueprint"
